   name: Greet First-Time Contributors
   on:
     issues:
       types: [opened]
   jobs:
     greeting:
       runs-on: ubuntu-latest
       steps:
         - name: Welcome Message
           uses: actions/first-interaction@v1
           with:
             repo-token: ${{ secrets.GITHUB_TOKEN }}
             issue-message: 'Thanks for opening your first issue!'
             pr-message: 'Thanks for your first contribution!'
